project:
  type: website

website:
  title: "Patricia Schenfeld"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About
      - href: slides/slides.ipynb
        text: Slides
bibliography: reference.bib

format:
  html:
    theme: cosmo
    toc: true



